
remote_theme: pmarsceill/just-the-docs

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: salapayca/spatialdecision
